

--below is the sql code for the project database
--DROP DATABASE IF EXISTS KEMRI_VISITORS_PROJECT;

CREATE DATABASE KEMRI_VISITORS_PROJECT;

USE KEMRI_VISITORS_PROJECT;


DROP TABLE IF EXISTS SECURITY_STAFF;

CREATE TABLE SECURITY_STAFF(
STAFF_NUMBER VARCHAR(20) NOT NULL,
STAFF_NAME VARCHAR(100) NOT NULL,
STAFF_PHONE_NUMBER VARCHAR(10) NOT NULL,
STAFF_PASSWORD VARCHAR(20) NOT NULL,
PRIMARY KEY(STAFF_NUMBER)
);


DROP TABLE IF EXISTS VISITOR;

CREATE TABLE VISITOR(
VISITOR_ID_NUMBER VARCHAR(8) NOT NULL,
VISITOR_NAME VARCHAR(100) NOT NULL,
VISITOR_PHONE_NUMBER VARCHAR(10),
PRIMARY KEY(VISITOR_ID_NUMBER)
);


DROP TABLE IF EXISTS DESTINATION;

CREATE TABLE DESTINATION(
DESTINATION_ID VARCHAR(10) NOT NULL,
DESTINATION_NAME VARCHAR(100) NOT NULL,
PRIMARY KEY(DESTINATION_ID)
);

INSERT INTO DESTINATION(DESTINATION_ID, DESTINATION_NAME) VALUES("ICT", "ICT Help Desk and User Support"),
("HRM", "Human Resource Management"),
("DAD", "Data Analysis Department"),
("PJT", "Project"),
("LAB", "Bio-medical Laboratory"),
("SCI", "Science Department"),
("RCH", "Research");


DROP TABLE IF EXISTS VISIT;

CREATE TABLE VISIT(
VISIT_DATE DATE NOT NULL,
VISIT_NUMBER INT NOT NULL,
VISITOR_ID_NUMBER VARCHAR(8) NOT NULL,
VISITOR_ORIGIN VARCHAR(100) NOT NULL,
VISITOR_DESTINATION_ID VARCHAR(10) NOT NULL,
VISIT_REASON VARCHAR(200) NOT NULL,
VISITOR_TIME_IN TIMESTAMP NOT NULL,
VISITOR_TIME_OUT TIMESTAMP NULL,
VEHICLE_NUMBER_PLATE VARCHAR(10),
PRIMARY KEY(VISIT_DATE, VISIT_NUMBER),
FOREIGN KEY (VISITOR_ID_NUMBER) REFERENCES VISITOR(VISITOR_ID_NUMBER),
FOREIGN KEY (VISITOR_DESTINATION_ID) REFERENCES DESTINATION(DESTINATION_ID)
);


DROP TABLE IF EXISTS DATE_NUMBER;

CREATE TABLE DATE_NUMBER(
DATE_TODAY VARCHAR(12) NOT NULL,
CURRENT_COUNT INT NOT NULL,
PRIMARY KEY( DATE_TODAY )
);

INSERT INTO DATE_NUMBER VALUES ("2024 05 12", 0);

--end of sql code
